In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("./테슬라 총합.csv")
df

,Unnamed: 0,date,tesla,tesla_거래량,tesla_volatility,elec_fee,oli_price,oli_price_volatility,carbon_credits,carbon_credits_volatility,...,dollar,dollar_volatility,alu_price,alu_vol,alu_change,cu_price,cu_change,REGI_price,REGI_vol,REGI_change
0,0,2015-01-02,43.86,23820.0,-1.39,6.67,52.69,-3.44,7.01,-3.31,...,91.08,0.90,1828.00,31.38,-1.12,6250.25,-0.55,9.79,436.60,0.82
1,1,2015-01-05,42.02,26840.0,-4.20,6.67,50.04,-5.03,6.90,-1.57,...,91.38,0.33,1812.25,43.25,-0.86,6142.00,-1.73,9.55,481.67,-2.45
2,2,2015-01-06,42.26,31310.0,0.57,6.67,47.93,-4.22,6.77,-1.88,...,91.50,0.13,1780.25,56.01,-1.77,6131.00,-0.18,9.12,534.76,-4.50
3,3,2015-01-07,42.19,14840.0,-0.17,6.67,48.65,1.50,6.78,0.15,...,91.89,0.43,1783.50,61.45,0.18,6125.00,-0.10,9.19,267.66,0.77
4,4,2015-01-08,42.12,17210.0,-0.17,6.67,48.79,0.29,6.81,0.44,...,92.37,0.52,1825.50,75.03,2.35,6122.75,-0.04,9.43,359.25,2.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,1802,2022-02-28,870.43,32770.0,7.48,7.16,95.72,4.51,82.65,-5.83,...,96.71,0.10,3368.50,85.69,0.33,9883.50,0.11,61.50,12740.00,40.38
1803,1803,2022-03-01,864.37,24720.0,-0.70,7.16,103.41,8.03,69.74,-15.62,...,97.41,0.73,3478.00,68.56,3.25,10061.50,1.80,60.75,4790.00,-1.22
1804,1804,2022-03-02,879.89,24650.0,1.80,7.16,110.60,6.95,67.72,-2.90,...,97.39,-0.02,3569.00,68.40,2.62,10166.00,1.04,60.86,5040.00,0.18
1805,1805,2022-03-03,839.29,20260.0,-4.61,7.16,107.67,-2.65,67.01,-1.05,...,97.79,0.41,3716.50,106.23,4.13,10351.00,1.82,61.26,5430.00,0.66
1806,1806,2022-03-04,838.29,22390.0,-0.12,7.16,115.68,7.44,65.80,-1.81,...,98.65,0.88,3849.00,106.23,3.57,10674.00,3.12,61.04,4290.00,-0.36

In [3]:
# df_mine = df[['date', 'tesla', 'tesla_거래량', 'tesla_volatility','EVE종가', 'EVE거래량', 'EVE변동률','BYD종가',\
# 'BYD거래량', 'BYD변동률','LIT조정종가', 'LIT거래량', 'SGL종가', 'SGL변동률','li_price',\
# 'nasdaq', 'nasdaq_거래량', 'nasdaq_volatility',]]

In [17]:
y = df['tesla']
x = df.drop(['tesla', 'Unnamed: 0','date'], axis = 1)

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.2, random_state=111)

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [20]:
lr = LinearRegression()

In [21]:
lr.fit(x_train, y_train)

ValueError: could not convert string to float: '1,013.39'