In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
price_df = pd.read_csv('./수정주가.csv', encoding='euckr').head()

In [20]:
raw_df = pd.read_excel('./재무데이터 수정.xlsx')

In [21]:
raw_df.T

,0,1,2,3,4,5,6,7,8,9,...,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053
Symbol,NaN,A005930,A000660,A068270,A207940,A005380,A005490,A051910,A035420,A028260,...,A303030,A267320,A271740,A257730,A232330,A297570,A279410,A258790,A264290,A010400
Symbol Name,NaN,삼성전자,SK하이닉스,셀트리온,삼성바이오로직스,현대차,POSCO,LG화학,NAVER,삼성물산,...,대신밸런스제5호스팩,교보7호스팩,한국제5호스팩,신한제3호스팩,SK3호스팩,IBKS제9호스팩,한화에이스스팩4호,케이비제11호스팩,한화에이스스팩3호,우진아이엔에스
ROA,08/4Q,7.62,0,2.92,0,4.5,12.01,12.47,36.21,0.44,...,0,0,0,0,0,0,0,0,0,0
ROA.1,09/1Q,5.24,0,4.89,0,3.94,10.04,12.54,34.97,0,...,0,0,0,0,0,0,0,0,0,0
ROA.2,09/2Q,3.78,0,8.63,0,4.67,7.16,12.97,34.45,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
DPS.34,17/2Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.35,17/3Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.36,17/4Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.37,18/1Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0
DPS.38,18/2Q,850,1000,19.61,0,4000,8000,6000,289.2,2000,...,0,0,0,0,0,0,0,0,0,0

In [22]:
raw_df.columns

Index(['Symbol', 'Symbol Name', 'ROA', 'ROA.1', 'ROA.2', 'ROA.3', 'ROA.4',
       'ROA.5', 'ROA.6', 'ROA.7',
       ...
       'DPS.29', 'DPS.30', 'DPS.31', 'DPS.32', 'DPS.33', 'DPS.34', 'DPS.35',
       'DPS.36', 'DPS.37', 'DPS.38'],
      dtype='object', length=651)

In [23]:
big_col = list(raw_df.columns)

In [24]:
big_col

['Symbol',
 'Symbol Name',
 'ROA',
 'ROA.1',
 'ROA.2',
 'ROA.3',
 'ROA.4',
 'ROA.5',
 'ROA.6',
 'ROA.7',
 'ROA.8',
 'ROA.9',
 'ROA.10',
 'ROA.11',
 'ROA.12',
 'ROA.13',
 'ROA.14',
 'ROA.15',
 'ROA.16',
 'ROA.17',
 'ROA.18',
 'ROA.19',
 'ROA.20',
 'ROA.21',
 'ROA.22',
 'ROA.23',
 'ROA.24',
 'ROA.25',
 'ROA.26',
 'ROA.27',
 'ROA.28',
 'ROA.29',
 'ROA.30',
 'ROA.31',
 'ROA.32',
 'ROA.33',
 'ROA.34',
 'ROA.35',
 'ROA.36',
 'ROA.37',
 'ROA.38',
 '부채비율',
 '부채비율.1',
 '부채비율.2',
 '부채비율.3',
 '부채비율.4',
 '부채비율.5',
 '부채비율.6',
 '부채비율.7',
 '부채비율.8',
 '부채비율.9',
 '부채비율.10',
 '부채비율.11',
 '부채비율.12',
 '부채비율.13',
 '부채비율.14',
 '부채비율.15',
 '부채비율.16',
 '부채비율.17',
 '부채비율.18',
 '부채비율.19',
 '부채비율.20',
 '부채비율.21',
 '부채비율.22',
 '부채비율.23',
 '부채비율.24',
 '부채비율.25',
 '부채비율.26',
 '부채비율.27',
 '부채비율.28',
 '부채비율.29',
 '부채비율.30',
 '부채비율.31',
 '부채비율.32',
 '부채비율.33',
 '부채비율.34',
 '부채비율.35',
 '부채비율.36',
 '부채비율.37',
 '부채비율.38',
 'PER',
 'PER.1',
 'PER.2',
 'PER.3',
 'PER.4',
 'PER.5',
 'PER.6',
 'PER.7',
 'PER.8',
 'PER.9',
 'PER.10',
 'PER.11',
 'PER.12',
 'PER.13',
 'PER.14',
 'PER.15',
 'PER.16',
 'PER.17',
 'PER.18',
 'PER.19',
 'PER.20',
 'PER.21',
 'PER.22',
 'PER.23',
 'PER.24',
 'PER.25',
 'PER.26',
 'PER.27',
 'PER.28',
 'PER.29',
 'PER.30',
 'PER.31',
 'PER.32',
 'PER.33',
 'PER.34',
 'PER.35',
 'PER.36',
 'PER.37',
 'PER.38',
 'PER.39',
 'PBR',
 'PBR.1',
 'PBR.2',
 'PBR.3',
 'PBR.4',
 'PBR.5',
 'PBR.6',
 'PBR.7',
 'PBR.8',
 'PBR.9',
 'PBR.10',
 'PBR.11',
 'PBR.12',
 'PBR.13',
 'PBR.14',
 'PBR.15',
 'PBR.16',
 'PBR.17',
 'PBR.18',
 'PBR.19',
 'PBR.20',
 'PBR.21',
 'PBR.22',
 'PBR.23',
 'PBR.24',
 'PBR.25',
 'PBR.26',
 'PBR.27',
 'PBR.28',
 'PBR.29',
 'PBR.30',
 'PBR.31',
 'PBR.32',
 'PBR.33',
 'PBR.34',
 'PBR.35',
 'PBR.36',
 'PBR.37',
 'PBR.38',
 'PBR.39',
 'PSR',
 'PSR.1',
 'PSR.2',
 'PSR.3',
 'PSR.4',
 'PSR.5',
 'PSR.6',
 'PSR.7',
 'PSR.8',
 'PSR.9',
 'PSR.10',
 'PSR.11',
 'PSR.12',
 'PSR.13',
 'PSR.14',
 'PSR.15',
 'PSR.16',
 'PSR.17',
 'PSR.18',
 'PSR.19',
 'PSR.20',
 'PSR.21',
 'PSR.22',
 'PSR.23',
 'PSR.24',
 'PSR.25',
 'PSR.26',
 'PSR.27',
 'PSR.28',
 'PSR.29',
 'PSR.30',
 'PSR.31',
 'PSR.32',
 'PSR.33',
 'PSR.34',
 'PSR.35',
 'PSR.36',
 'PSR.37',
 'PSR.38',
 'EV',
 'EV.1',
 'EV.2',
 'EV.3',
 'EV.4',
 'EV.5',
 'EV.6',
 'EV.7',
 'EV.8',
 'EV.9',
 'EV.10',
 'EV.11',
 'EV.12',
 'EV.13',
 'EV.14',
 'EV.15',
 'EV.16',
 'EV.17',
 'EV.18',
 'EV.19',
 'EV.20',
 'EV.21',
 'EV.22',
 'EV.23',
 'EV.24',
 'EV.25',
 'EV.26',
 'EV.27',
 'EV.28',
 'EV.29',
 'EV.30',
 'EV.31',
 'EV.32',
 'EV.33',
 'EV.34',
 'EV.35',
 'EV.36',
 'EV.37',
 'EV.38',
 'EBITDA',
 'EBITDA.1',
 'EBITDA.2',
 'EBITDA.3',
 'EBITDA.4',
 'EBITDA.5',
 'EBITDA.6',
 'EBITDA.7',
 'EBITDA.8',
 'EBITDA.9',
 'EBITDA.10',
 'EBITDA.11',
 'EBITDA.12',
 'EBITDA.13',
 'EBITDA.14',
 'EBITDA.15',
 'EBITDA.16',
 'EBITDA.17',
 'EBITDA.18',
 'EBITDA.19',
 'EBITDA.20',
 'EBITDA.21',
 'EBITDA.22',
 'EBITDA.23',
 'EBITDA.24',
 'EBITDA.25',
 'EBITDA.26',
 'EBITDA.27',
 'EBITDA.28',
 'EBITDA.29',
 'EBITDA.30',
 'EBITDA.31',
 'EBITDA.32',
 'EBITDA.33',
 'EBITDA.34',
 'EBITDA.35',
 'EBITDA.36',
 'EBITDA.37',
 'EBITDA.38',
 'EV/EBITDA',
 'EV/EBITDA.1',
 'EV/EBITDA.2',
 'EV/EBITDA.3',
 'EV/EBITDA.4',
 'EV/EBITDA.5',
 'EV/EBITDA.6',
 'EV/EBITDA.7',
 'EV/EBITDA.8',
 'EV/EBITDA.9',
 'EV/EBITDA.10',
 'EV/EBITDA.11',
 'EV/EBITDA.12',
 'EV/EBITDA.13',
 'EV/EBITDA.14',
 'EV/EBITDA.15',
 'EV/EBITDA.16',
 'EV/EBITDA.17',
 'EV/EBITDA.18',
 'EV/EBITDA.19',
 'EV/EBITDA.20',
 'EV/EBITDA.21',
 'EV/EBITDA.22',
 'EV/EBITDA.23',
 'EV/EBITDA.24',
 'EV/EBITDA.25',
 'EV/EBITDA.26',
 'EV/EBITDA.27',
 'EV/EBITDA.28',
 'EV/EBITDA.29',
 'EV/EBITDA.30',
 'EV/EBITDA.31',
 'EV/EBITDA.32',
 'EV/EBITDA.33',
 'EV/EBITDA.34',
 'EV/EBITDA.35',
 'EV/EBITDA.36',
 'EV/EBITDA.37',
 'EV/EBITDA.38',
 '유동자산',
 '유동자산.1',
 '유동자산.2',
 '유동자산.3',
 '유동자산.4',
 '유동자산.5',
 '유동자산.6',
 '유동자산.7',
 '유동자산.8',
 '내돈',
 '내돈.1',
 '내돈.2',
 '내돈.3',
 '내돈.4',
 '내돈.5',
 '내돈.6',
 '내돈.7',
 '내돈.8',
 '내돈.9',
 '내돈.10',
 '내돈.11',
 '내돈.12',
 '내돈.13',
 '내돈.14',
 '내돈.15',
 '내돈.16',
 '내돈.17',
 '내돈.18',
 '내돈.19',
 '내돈.20',
 '내돈.21',
 '내돈.22',
 '내돈.23',
 '내돈.24',
 '내돈.25',
 '내돈.26',
 '내돈.27',
 '내돈.28',
 '내돈.29',
 '내돈.30',
 '내돈.31',
 '내돈.32',
 '내돈.33',
 '내돈.34',
 '내돈.35',
 '내돈.36',
 '내돈.37',
 '내돈.38',
 '내돈.39',
 '시총',
 '시총.1',
 '시총.2',
 '시총.3',
 '시총.4',
 '시총.5',
 '시총.6',
 '시총.7',
 '시총.8',
 '시총.9',
 '시총.10',
 '시총.11',
 '시총.12',
 '시총.13',
 '시총.14',
 '시총.15',
 '시총.16',
 '시총.17',
 '시총.18',
 '시총.19',
 '시총.20',
 '시총.21',
 '시총.22',
 '시총.23',
 '시총.24',
 '시총.25',
 '시총.26',
 '시총.27',
 '시총.28',
 '시총.29',
 '시총.30',
 '시총.31',
 '시총.32',
 '시총.33',
 '시총.34',
 '시총.35',
 '시총.36',
 '시총.37',
 '시총.38',
 '시총.39',
 '영익',
 '영익.1',
 '영익.2',
 '영익.3',
 '영익.4',
 '영익.5',
 '영익.6',
 '영익.7',
 '영익.8',
 '영익.9',
 '영익.10',
 '영익.11',
 '영익.12',
 '영익.13',
 '영익.14',
 '영익.15',
 '영익.16',
 '영익.17',
 '영익.18',
 '영익.19',
 '영익.20',
 '영익.21',
 '영익.22',
 '영익.23',
 '영익.24',
 '영익.25',
 '영익.26',
 '영익.27',
 '영익.28',
 '영익.29',
 '영익.30',
 '영익.31',
 '영익.32',
 '영익.33',
 '영익.34',
 '영익.35',
 '영익.36',
 '영익.37',
 '영익.38',
 '영익.39',
 '순익',
 '순익.1',
 '순익.2',
 '순익.3',
 '순익.4',
 '순익.5',
 '순익.6',
 '순익.7',
 '순익.8',
 '순익.9',
 '순익.10',
 '순익.11',
 '순익.12',
 '순익.13',
 '순익.14',
 '순익.15',
 '순익.16',
 '순익.17',
 '순익.18',
 '순익.19',
 '순익.20',
 '순익.21',
 '순익.22',
 '순익.23',
 '순익.24',
 '순익.25',
 '순익.26',
 '순익.27',
 '순익.28',
 '순익.29',
 '순익.30',
 '순익.31',
 '순익.32',
 '순익.33',
 '순익.34',
 '순익.35',
 '순익.36',
 '순익.37',
 '순익.38',
 '순익.39',
 '영업활동현흐',
 '영업활동현흐.1',
 '영업활동현흐.2',
 '영업활동현흐.3',
 '영업활동현흐.4',
 '영업활동현흐.5',
 '영업활동현흐.6',
 '영업활동현흐.7',
 '영업활동현흐.8',
 '영업활동현흐.9',
 '영업활동현흐.10',
 '영업활동현흐.11',
 '영업활동현흐.12',
 '영업활동현흐.13',
 '영업활동현흐.14',
 '영업활동현흐.15',
 '영업활동현흐.16',
 '영업활동현흐.17',
 '영업활동현흐.18',
 '영업활동현흐.19',
 '영업활동현흐.20',
 '영업활동현흐.21',
 '영업활동현흐.22',
 '영업활동현흐.23',
 '영업활동현흐.24',
 '영업활동현흐.25',
 '영업활동현흐.26',
 '영업활동현흐.27',
 '영업활동현흐.28',
 '영업활동현흐.29',
 '영업활동현흐.30',
 '영업활동현흐.31',
 '영업활동현흐.32',
 '영업활동현흐.33',
 '영업활동현흐.34',
 '영업활동현흐.35',
 '영업활동현흐.36',
 '영업활동현흐.37',
 '영업활동현흐.38',
 '매출총이익율',
 '매출총이익율.1',
 '매출총이익율.2',
 '매출총이익율.3',
 '매출총이익율.4',
 '매출총이익율.5',
 '매출총이익율.6',
 '매출총이익율.7',
 '매출총이익율.8',
 '매출총이익율.9',
 '매출총이익율.10',
 '매출총이익율.11',
 '매출총이익율.12',
 '매출총이익율.13',
 '매출총이익율.14',
 '매출총이익율.15',
 '매출총이익율.16',
 '매출총이익율.17',
 '매출총이익율.18',
 '매출총이익율.19',
 '매출총이익율.20',
 '매출총이익율.21',
 '매출총이익율.22',
 '매출총이익율.23',
 '매출총이익율.24',
 '매출총이익율.25',
 '매출총이익율.26',
 '매출총이익율.27',
 '매출총이익율.28',
 '매출총이익율.29',
 '매출총이익율.30',
 '매출총이익율.31',
 '매출총이익율.32',
 '매출총이익율.33',
 '매출총이익율.34',
 '매출총이익율.35',
 '매출총이익율.36',
 '매출총이익율.37',
 '매출총이익율.38',
 '매출',
 '매출.1',
 '매출.2',
 '매출.3',
 '매출.4',
 '매출.5',
 '매출.6',
 '매출.7',
 '매출.8',
 '매출.9',
 '매출.10',
 '매출.11',
 '매출.12',
 '매출.13',
 '매출.14',
 '매출.15',
 '매출.16',
 '매출.17',
 '매출.18',
 '매출.19',
 '매출.20',
 '매출.21',
 '매출.22',
 '매출.23',
 '매출.24',
 '매출.25',
 '매출.26',
 '매출.27',
 '매출.28',
 '매출.29',
 '매출.30',
 '매출.31',
 '매출.32',
 '매출.33',
 '매출.34',
 '매출.35',
 '매출.36',
 '매출.37',
 '매출.38',
 '매출.39',
 '총자산',
 '총자산.1',
 '총자산.2',
 '총자산.3',
 '총자산.4',
 '총자산.5',
 '총자산.6',
 '총자산.7',
 '총자산.8',
 'DPS',
 'DPS.1',
 'DPS.2',
 'DPS.3',
 'DPS.4',
 'DPS.5',
 'DPS.6',
 'DPS.7',
 'DPS.8',
 'DPS.9',
 'DPS.10',
 'DPS.11',
 'DPS.12',
 'DPS.13',
 'DPS.14',
 'DPS.15',
 'DPS.16',
 'DPS.17',
 'DPS.18',
 'DPS.19',
 'DPS.20',
 'DPS.21',
 'DPS.22',
 'DPS.23',
 'DPS.24',
 'DPS.25',
 'DPS.26',
 'DPS.27',
 'DPS.28',
 'DPS.29',
 'DPS.30',
 'DPS.31',
 'DPS.32',
 'DPS.33',
 'DPS.34',
 'DPS.35',
 'DPS.36',
 'DPS.37',
 'DPS.38']

In [25]:
new_big_col = []
for i in big_col:
    new_big_col.append(i.split('.')[0])

In [26]:
new_big_col

['Symbol',
 'Symbol Name',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 'ROA',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 '부채비율',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PER',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PBR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'PSR',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EV',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 'EV/EBITDA',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '유동자산',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '내돈',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '시총',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '영익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '순익',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '영업활동현흐',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출총이익율',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '매출',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 '총자산',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS',
 'DPS']

In [27]:
small_col = list(raw_df.loc[0])

In [28]:
small_col

[nan,
 nan,
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q']

In [29]:
small_col[0] = new_big_col[0]
small_col[1] = new_big_col[1]

In [30]:
small_col

['Symbol',
 'Symbol Name',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q',
 '18/3Q',
 '9년',
 '10년',
 '11년',
 '12년',
 '13년',
 '14년',
 '15년',
 '16년',
 '17년',
 '08/4Q',
 '09/1Q',
 '09/2Q',
 '09/3Q',
 '09/4Q',
 '10/1Q',
 '10/2Q',
 '10/3Q',
 '10/4Q',
 '11/1Q',
 '11/2Q',
 '11/3Q',
 '11/4Q',
 '12/1Q',
 '12/2Q',
 '12/3Q',
 '12/4Q',
 '13/1Q',
 '13/2Q',
 '13/3Q',
 '13/4Q',
 '14/1Q',
 '14/2Q',
 '14/3Q',
 '14/4Q',
 '15/1Q',
 '15/2Q',
 '15/3Q',
 '15/4Q',
 '16/1Q',
 '16/2Q',
 '16/3Q',
 '16/4Q',
 '17/1Q',
 '17/2Q',
 '17/3Q',
 '17/4Q',
 '18/1Q',
 '18/2Q']

In [31]:
raw_df.columns = [new_big_col, small_col]
raw_df.columns

MultiIndex([(     'Symbol',      'Symbol'),
            ('Symbol Name', 'Symbol Name'),
            (        'ROA',       '08/4Q'),
            (        'ROA',       '09/1Q'),
            (        'ROA',       '09/2Q'),
            (        'ROA',       '09/3Q'),
            (        'ROA',       '09/4Q'),
            (        'ROA',       '10/1Q'),
            (        'ROA',       '10/2Q'),
            (        'ROA',       '10/3Q'),
            ...
            (        'DPS',       '16/1Q'),
            (        'DPS',       '16/2Q'),
            (        'DPS',       '16/3Q'),
            (        'DPS',       '16/4Q'),
            (        'DPS',       '17/1Q'),
            (        'DPS',       '17/2Q'),
            (        'DPS',       '17/3Q'),
            (        'DPS',       '17/4Q'),
            (        'DPS',       '18/1Q'),
            (        'DPS',       '18/2Q')],
           length=651)

In [32]:
raw_df.head()

    Symbol Symbol Name    ROA                                            \
    Symbol Symbol Name  08/4Q  09/1Q  09/2Q  09/3Q  09/4Q  10/1Q  10/2Q
0      NaN         NaN  08/4Q  09/1Q  09/2Q  09/3Q  09/4Q  10/1Q  10/2Q
1  A005930        삼성전자   7.62   5.24   3.78   5.46   6.93   8.74  10.53
2  A000660      SK하이닉스      0      0      0      0      0  12.57  18.73
3  A068270        셀트리온   2.92   4.89   8.63    7.3  10.48  11.75  14.02
4  A207940    삼성바이오로직스      0      0      0      0      0      0      0

          ...    DPS                                                          \
   10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q  18/1Q
0  10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q  18/1Q
1  11.46  ...    570    570    570    570    850    850    850    850    850
2  25.35  ...    600    600    600    600   1000   1000   1000   1000   1000
3  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61  19.61
4      0  ...      0      0      0      0      0      0      0      0      0


   18/2Q
0  18/2Q
1    850
2   1000
3  19.61
4      0

[5 rows x 651 columns]

In [33]:
raw_df.isnull().sum(axis=1)

0       2
1       0
2       0
3       0
4       0
       ..
2049    0
2050    0
2051    0
2052    0
2053    0
Length: 2054, dtype: int64

In [34]:
raw_df.isnull().sum(axis=1).sum()

2

In [35]:
finance_df = raw_df.drop(0)

In [36]:
finance_df.index = finance_df['Symbol']['Symbol']

In [37]:
finance_df

          Symbol Symbol Name   ROA                                         \
          Symbol Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q
Symbol
A005930  A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53
A000660  A000660      SK하이닉스     0     0     0     0      0  12.57  18.73
A068270  A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02
A207940  A207940    삼성바이오로직스     0     0     0     0      0      0      0
A005380  A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10
...          ...         ...   ...   ...   ...   ...    ...    ...    ...
A297570  A297570   IBKS제9호스팩     0     0     0     0      0      0      0
A279410  A279410   한화에이스스팩4호     0     0     0     0      0      0      0
A258790  A258790   케이비제11호스팩     0     0     0     0      0      0      0
A264290  A264290   한화에이스스팩3호     0     0     0     0      0      0      0
A010400  A010400     우진아이엔에스     0     0     0     0      0      0      0

                ...    DPS                                                   \
         10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930  11.46  ...    570    570    570    570    850    850    850    850
A000660  25.35  ...    600    600    600    600   1000   1000   1000   1000
A068270  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   9.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 651 columns]

In [38]:
finance_df.columns

MultiIndex([(     'Symbol',      'Symbol'),
            ('Symbol Name', 'Symbol Name'),
            (        'ROA',       '08/4Q'),
            (        'ROA',       '09/1Q'),
            (        'ROA',       '09/2Q'),
            (        'ROA',       '09/3Q'),
            (        'ROA',       '09/4Q'),
            (        'ROA',       '10/1Q'),
            (        'ROA',       '10/2Q'),
            (        'ROA',       '10/3Q'),
            ...
            (        'DPS',       '16/1Q'),
            (        'DPS',       '16/2Q'),
            (        'DPS',       '16/3Q'),
            (        'DPS',       '16/4Q'),
            (        'DPS',       '17/1Q'),
            (        'DPS',       '17/2Q'),
            (        'DPS',       '17/3Q'),
            (        'DPS',       '17/4Q'),
            (        'DPS',       '18/1Q'),
            (        'DPS',       '18/2Q')],
           length=651)

In [39]:
finance_df

          Symbol Symbol Name   ROA                                         \
          Symbol Symbol Name 08/4Q 09/1Q 09/2Q 09/3Q  09/4Q  10/1Q  10/2Q
Symbol
A005930  A005930        삼성전자  7.62  5.24  3.78  5.46   6.93   8.74  10.53
A000660  A000660      SK하이닉스     0     0     0     0      0  12.57  18.73
A068270  A068270        셀트리온  2.92  4.89  8.63   7.3  10.48  11.75  14.02
A207940  A207940    삼성바이오로직스     0     0     0     0      0      0      0
A005380  A005380         현대차   4.5  3.94  4.67   6.6   8.36  10.01     10
...          ...         ...   ...   ...   ...   ...    ...    ...    ...
A297570  A297570   IBKS제9호스팩     0     0     0     0      0      0      0
A279410  A279410   한화에이스스팩4호     0     0     0     0      0      0      0
A258790  A258790   케이비제11호스팩     0     0     0     0      0      0      0
A264290  A264290   한화에이스스팩3호     0     0     0     0      0      0      0
A010400  A010400     우진아이엔에스     0     0     0     0      0      0      0

                ...    DPS                                                   \
         10/3Q  ...  16/1Q  16/2Q  16/3Q  16/4Q  17/1Q  17/2Q  17/3Q  17/4Q
Symbol          ...
A005930  11.46  ...    570    570    570    570    850    850    850    850
A000660  25.35  ...    600    600    600    600   1000   1000   1000   1000
A068270  17.22  ...  46.73  46.73  46.73  46.73  19.61  19.61  19.61  19.61
A207940      0  ...      0      0      0      0      0      0      0      0
A005380   9.82  ...   4000   4000   4000   4000   4000   4000   4000   4000
...        ...  ...    ...    ...    ...    ...    ...    ...    ...    ...
A297570      0  ...      0      0      0      0      0      0      0      0
A279410      0  ...      0      0      0      0      0      0      0      0
A258790      0  ...      0      0      0      0      0      0      0      0
A264290      0  ...      0      0      0      0      0      0      0      0
A010400      0  ...      0      0      0      0      0      0      0      0


         18/1Q  18/2Q
Symbol
A005930    850    850
A000660   1000   1000
A068270  19.61  19.61
A207940      0      0
A005380   4000   4000
...        ...    ...
A297570      0      0
A279410      0      0
A258790      0      0
A264290      0      0
A010400      0      0

[2053 rows x 651 columns]

In [40]:
date = '17/2Q'
finance_df[[('PBR', date), ('ROA', date)]]

          PBR    ROA
        17/2Q  17/2Q
Symbol
A005930   1.6  10.95
A000660  1.77  17.58
A068270  6.41   9.61
A207940   4.8      0
A005380  0.51   2.43
...       ...    ...
A297570     0      0
A279410     0      0
A258790   1.1      0
A264290  1.22      0
A010400     0   3.29

[2053 rows x 2 columns]

In [41]:
def finance_data_preprocessing(path):
    raw_data = pd.read_excel(path)
    
    big_col = list(raw_data.columns)
    for num, temp in enumerate(big_col):
        if '.' in temp:
            big_col[num] = temp.split('.')[0]
            
        small_col = list(raw_data.loc[0])
        small_col[0] = big_col[0]
        small_col[1] = big_col[1]

        raw_data.columns = [big_col, small_col]
        raw_data = raw_data.drop(0)

        raw_data.index = raw_data['Symbol']['Symbol']
        del raw_data['Symbol']

        return raw_data

In [42]:
finance_data_preprocessing('./재무데이터 수정.xlsx')

,Symbol Name,ROA,ROA.1,ROA.2,ROA.3,ROA.4,ROA.5,ROA.6,ROA.7,ROA.8,...,DPS.29,DPS.30,DPS.31,DPS.32,DPS.33,DPS.34,DPS.35,DPS.36,DPS.37,DPS.38
,Symbol Name,08/4Q,09/1Q,09/2Q,09/3Q,09/4Q,10/1Q,10/2Q,10/3Q,10/4Q,...,16/1Q,16/2Q,16/3Q,16/4Q,17/1Q,17/2Q,17/3Q,17/4Q,18/1Q,18/2Q
Symbol,,,,,,,,,,,,,,,,,,,,,
A005930,삼성전자,7.62,5.24,3.78,5.46,6.93,8.74,10.53,11.46,12.1,...,570,570,570,570,850,850,850,850,850,850
A000660,SK하이닉스,0,0,0,0,0,12.57,18.73,25.35,17.41,...,600,600,600,600,1000,1000,1000,1000,1000,1000
A068270,셀트리온,2.92,4.89,8.63,7.3,10.48,11.75,14.02,17.22,9.68,...,46.73,46.73,46.73,46.73,19.61,19.61,19.61,19.61,19.61,19.61
A207940,삼성바이오로직스,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A005380,현대차,4.5,3.94,4.67,6.6,8.36,10.01,10,9.82,7.82,...,4000,4000,4000,4000,4000,4000,4000,4000,4000,4000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A297570,IBKS제9호스팩,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A279410,한화에이스스팩4호,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A258790,케이비제11호스팩,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A264290,한화에이스스팩3호,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A010400,우진아이엔에스,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
price_raw = pd.read_csv('./수정주가.csv', encoding='euckr')

In [44]:
price_df = price_raw.drop(0)

In [45]:
price_df.index = pd.to_datetime(price_df['코드명'])
price_df.drop(['코드명'], axis=1, inplace=True)

In [49]:
price_df

,A000010,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000090,A000100,...,A900340,A950010,A950030,A950070,A950100,A950110,A950130,A950140,A950160,A950170
코드명,,,,,,,,,,,,,,,,,,,,,
2006-01-31,NaN,3430,NaN,2317,12164,5788,57432,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-28,NaN,3440,NaN,2279,9693,5015,55082,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-31,NaN,3080,NaN,2039,10187,4775,58556,NaN,NaN,111188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-04-28,NaN,5040,NaN,1918,10985,6060,62133,NaN,NaN,108050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-05-30,NaN,5500,NaN,1332,10643,6008,57432,NaN,NaN,101079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-31,NaN,9050,15750,558,11850,18200,86300,15750,NaN,160283,...,NaN,NaN,NaN,NaN,NaN,7150,3985,5610,34000,6570
2018-11-30,NaN,9110,15650,512,11250,21200,87500,17500,NaN,217698,...,2340,NaN,NaN,NaN,NaN,15300,4150,7290,41900,8200
2018-12-28,NaN,9100,15600,500,10800,21850,78500,16600,NaN,204500,...,1395,NaN,NaN,NaN,NaN,16300,4285,6230,43150,6730
2019-01-31,NaN,9840,14800,528,11000,22200,83200,16900,NaN,238000,...,1535,NaN,NaN,NaN,NaN,14200,4015,5490,39200,7120
2019-02-28,NaN,9800,NaN,507,11250,22100,84300,17700,NaN,260500,...,2290,NaN,NaN,NaN,NaN,12600,3980,5490,40300,8710

In [47]:
def price_data_preprocs(path):
    price_raw = pd.read_csv(path, encoding='euckr')
    price_df = price_raw.drop(0)
    price_df.index = pd.to_datetime(price_df['코드명'])
    del price_df['코드명']
    return price_df

In [48]:
price_data_preprocs('./수정주가.csv')

,A000010,A000020,A000030,A000040,A000050,A000060,A000070,A000080,A000090,A000100,...,A900340,A950010,A950030,A950070,A950100,A950110,A950130,A950140,A950160,A950170
코드명,,,,,,,,,,,,,,,,,,,,,
2006-01-31,NaN,3430,NaN,2317,12164,5788,57432,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-02-28,NaN,3440,NaN,2279,9693,5015,55082,NaN,NaN,120947,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-03-31,NaN,3080,NaN,2039,10187,4775,58556,NaN,NaN,111188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-04-28,NaN,5040,NaN,1918,10985,6060,62133,NaN,NaN,108050,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-05-30,NaN,5500,NaN,1332,10643,6008,57432,NaN,NaN,101079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-10-31,NaN,9050,15750,558,11850,18200,86300,15750,NaN,160283,...,NaN,NaN,NaN,NaN,NaN,7150,3985,5610,34000,6570
2018-11-30,NaN,9110,15650,512,11250,21200,87500,17500,NaN,217698,...,2340,NaN,NaN,NaN,NaN,15300,4150,7290,41900,8200
2018-12-28,NaN,9100,15600,500,10800,21850,78500,16600,NaN,204500,...,1395,NaN,NaN,NaN,NaN,16300,4285,6230,43150,6730
2019-01-31,NaN,9840,14800,528,11000,22200,83200,16900,NaN,238000,...,1535,NaN,NaN,NaN,NaN,14200,4015,5490,39200,7120
2019-02-28,NaN,9800,NaN,507,11250,22100,84300,17700,NaN,260500,...,2290,NaN,NaN,NaN,NaN,12600,3980,5490,40300,8710

In [51]:
data_df = finance_data_preprocessing('재무데이터 수정.xlsx')

date = '17/4Q'
fin_df = data_df[[('시총', date), ('PER', date), ('PBR', date), ('PSR', date),('Symbol Name', 'Symbol Name')]]

KeyError: "[('시총', '17/4Q'), ('PER', '17/4Q'), ('PBR', '17/4Q'), ('PSR', '17/4Q')] not in index"

In [ ]:
fin_df

In [ ]:
fin_df['시총'][date] = pd.to_numeric(fin_df['시총'][date])

In [ ]:
fin_df1 = fin_df[fin_df['시총'][date] > 0]

In [ ]:
fin_df2 = fin_df1['PER'][date] > 0
fin_df3 = fin_df2['PBR'][date] > 0

In [ ]:
fin_df3

In [ ]:
def LSV(path, date):
    data_df = finance_data_preprocessing('재무데이터 수정.xlsx')

    date = '17/4Q'
    fin_df = data_df[[('시총', date), ('PER', date), ('PBR', date), ('PSR', date),('Symbol Name', 'Symbol Name')]]